-- Hapus data yang mungkin sudah ada (opsional, hati-hati jika sudah ada transaksi)
TRUNCATE TABLE sumber_donasi CASCADE;
TRUNCATE TABLE seksi CASCADE;

-- Insert data untuk tabel sumber_donasi
INSERT INTO sumber_donasi (nama, urutan) VALUES 
('BANDUNG', 1),
('BATANG', 2),
('Belum Konfirmasi', 3),
('BOJONEGORO 1 - KAPAS', 4),
('BOJONEGORO 2 - SEKAR', 5),
('CIREBON', 6),
('DEMAK 1 - WONOKETINGAL', 7),
('DEMAK 2 - DEMPET', 8),
('DEMAK 3 (MRANGGEN)', 9),
('GARUT', 10),
('GROBOGAN 1 - PURWODADI', 11),
('GROBOGAN 2 - GODONG', 12),
('JAKARTA SELATAN', 13),
('JAMBI', 14),
('JEPARA', 15),
('KENDAL 1 - CEPIRING', 16),
('KENDAL 2 - BOJA', 17),
('KENDAL BOTOMULYO', 18),
('KLATEN', 19),
('PALEMBANG - KOTA', 20),
('PALEMBANG - SEKAYU', 21),
('PEMALANG 1 - BELIK', 22),
('PEMALANG 2 - ULUJAMI', 23),
('PONOROGO', 24),
('PURWOREJO', 25),
('RIAU', 26),
('SEMARANG - CANDILAMA', 27),
('SEMARANG - GENUK', 28),
('SEMARANG - KROBOKAN', 29),
('SEMARANG - MIJEN', 30),
('SEMARANG - NGALIYAN', 31),
('SEMARANG - PEDURUNGAN', 32),
('SEMARANG - PUSAT', 33),
('SEMARANG KALICARI', 34),
('SOLO', 35),
('TANGERANG', 36),
('TEGAL 1 - KOTA', 37),
('TEGAL 2 - SLAWI', 38),
('TEGAL BARU', 39),
('TEMANGGUNG', 40),
('UNGARAN 1 - GOGIK', 41),
('UNGARAN 2 - JATIRUNGGO', 42),
('UNGARAN 3 - BABADAN', 43),
('YOGYAKARTA', 44);

-- Insert data untuk tabel seksi
INSERT INTO seksi (nama, rencana_anggaran, urutan) VALUES 
('SEKRETARIAT', 0, 1),
('PERIJINAN', 0, 2),
('HUMAS', 0, 3),
('PERLENGKAPAN', 0, 4),
('PERTUKANGAN', 0, 5),
('TRANSPORTASI', 0, 6),
('DOKUMENTASI', 0, 7),
('KONSUMSI', 0, 8),
('KEBERSIHAN', 0, 9),
('LISTRIK', 0, 10),
('AIR WUDHU MCK', 0, 11),
('SOUND SYSTEM', 0, 12),
('AIR MINUM & TANKI', 0, 13),
('KEAMANAN', 0, 14),
('PARKIR', 0, 15),
('KESEHATAN', 0, 16),
('UPACARA', 0, 17),
('PUBLIKASI', 0, 18);
